name: snake game from a github user contributions graph

on:
  # run automatically At 00:00:00am, on every Sunday, Tuesday, Thursday and Saturday, every month 
  schedule:
    - cron: "0 0 ? * SUN,TUE,THU,SAT" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/grid-snake.svg
            dist/grid-snake-dark.svg?palette=github-dark
            dist/grid-snake-white.svg?palette=github-light
            dist/grid-snake-ov.svg?color_snake=#f5ce1e&color_dots=#0d1117,#5ce1e6,#0bb5ff,#bdfffe,#609d9e
            dist/grid-snake-ov-white.svg?color_snake=#050a30&color_dots=#ffffff,#5ce1e6,#0bb5ff,#bdfffe,#609d9e
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
