name: Waka Readme

on:
  schedule:
    # Runs at 00:00, only on Sunday, Tuesday, Thursday, and Saturday.

    - cron: "0 0 ? * SUN,TUE,THU,SAT"

  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics

    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master

        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SHOW_OS: "True"

          SHOW_PROJECTS: "True"

          SHOW_PROFILE_VIEWS: "True"

          SHOW_EDITORS: "False"

          SHOW_LANGUAGE_PER_REPO: "True"

          SHOW_LOC_CHART: "False"

          SHOW_LINES_OF_CODE: "True"

          SHOW_SHORT_INFO: "False"
